/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.50
 * Generated at: 2026-03-23 10:58:39 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class customtag_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/WEB-INF/customtag.tld", Long.valueOf(1774263398000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fcustom_005fhellotag_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fcustom_005faddtag_0026_005fnum2_005fnum1_005fdescription_005fnobody;

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fcustom_005fhellotag_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fcustom_005faddtag_0026_005fnum2_005fnum1_005fdescription_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fcustom_005fhellotag_005fnobody.release();
    _005fjspx_005ftagPool_005fcustom_005faddtag_0026_005fnum2_005fnum1_005fdescription_005fnobody.release();
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"en\">\n");
      out.write("<head>\n");
      out.write("    <meta charset=\"UTF-8\">\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n");
      out.write("    <title>Custom Tag Demo</title>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("    <h1>Custom Tag Example</h1>\n");
      out.write("    <h2>HelloTag Output</h2>\n");
      out.write("    ");
      if (_jspx_meth_custom_005fhellotag_005f0(_jspx_page_context))
        return;
      out.write("\n");
      out.write("    <h2>AddTag Output</h2>\n");
      out.write("    <p>Example literal attributes:</p>\n");
      out.write("    ");
      if (_jspx_meth_custom_005faddtag_005f0(_jspx_page_context))
        return;
      out.write("\n");
      out.write("\n");
      out.write("    <p>Example with expression values (request params):</p>\n");
      out.write("    <form method=\"get\">\n");
      out.write("        <label>Num1: <input name=\"n1\" value=\"\" /></label>\n");
      out.write("        <label>Num2: <input name=\"n2\" value=\"\" /></label>\n");
      out.write("        <button type=\"submit\">Compute</button>\n");
      out.write("    </form>\n");
      out.write("    ");
      if (_jspx_meth_custom_005faddtag_005f1(_jspx_page_context))
        return;
      out.write("\n");
      out.write("</body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_custom_005fhellotag_005f0(jakarta.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    //  custom:hellotag
    com.practical6.HelloTag _jspx_th_custom_005fhellotag_005f0 = (com.practical6.HelloTag) _005fjspx_005ftagPool_005fcustom_005fhellotag_005fnobody.get(com.practical6.HelloTag.class);
    _jspx_th_custom_005fhellotag_005f0.setPageContext(_jspx_page_context);
    _jspx_th_custom_005fhellotag_005f0.setParent(null);
    int _jspx_eval_custom_005fhellotag_005f0 = _jspx_th_custom_005fhellotag_005f0.doStartTag();
    if (_jspx_th_custom_005fhellotag_005f0.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      return true;
    }
    _005fjspx_005ftagPool_005fcustom_005fhellotag_005fnobody.reuse(_jspx_th_custom_005fhellotag_005f0);
    return false;
  }

  private boolean _jspx_meth_custom_005faddtag_005f0(jakarta.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    //  custom:addtag
    com.practical6.AddTag _jspx_th_custom_005faddtag_005f0 = (com.practical6.AddTag) _005fjspx_005ftagPool_005fcustom_005faddtag_0026_005fnum2_005fnum1_005fdescription_005fnobody.get(com.practical6.AddTag.class);
    _jspx_th_custom_005faddtag_005f0.setPageContext(_jspx_page_context);
    _jspx_th_custom_005faddtag_005f0.setParent(null);
    // /customtag.jsp(16,4) name = num1 type = java.lang.String reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_custom_005faddtag_005f0.setNum1("12");
    // /customtag.jsp(16,4) name = num2 type = java.lang.String reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_custom_005faddtag_005f0.setNum2("30");
    // /customtag.jsp(16,4) name = description type = java.lang.String reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_custom_005faddtag_005f0.setDescription("Sum is:");
    int _jspx_eval_custom_005faddtag_005f0 = _jspx_th_custom_005faddtag_005f0.doStartTag();
    if (_jspx_th_custom_005faddtag_005f0.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      return true;
    }
    _005fjspx_005ftagPool_005fcustom_005faddtag_0026_005fnum2_005fnum1_005fdescription_005fnobody.reuse(_jspx_th_custom_005faddtag_005f0);
    return false;
  }

  private boolean _jspx_meth_custom_005faddtag_005f1(jakarta.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    //  custom:addtag
    com.practical6.AddTag _jspx_th_custom_005faddtag_005f1 = (com.practical6.AddTag) _005fjspx_005ftagPool_005fcustom_005faddtag_0026_005fnum2_005fnum1_005fdescription_005fnobody.get(com.practical6.AddTag.class);
    _jspx_th_custom_005faddtag_005f1.setPageContext(_jspx_page_context);
    _jspx_th_custom_005faddtag_005f1.setParent(null);
    // /customtag.jsp(24,4) name = num1 type = java.lang.String reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_custom_005faddtag_005f1.setNum1((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${param.n1}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
    // /customtag.jsp(24,4) name = num2 type = java.lang.String reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_custom_005faddtag_005f1.setNum2((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${param.n2}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
    // /customtag.jsp(24,4) name = description type = java.lang.String reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_custom_005faddtag_005f1.setDescription("From params:");
    int _jspx_eval_custom_005faddtag_005f1 = _jspx_th_custom_005faddtag_005f1.doStartTag();
    if (_jspx_th_custom_005faddtag_005f1.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      return true;
    }
    _005fjspx_005ftagPool_005fcustom_005faddtag_0026_005fnum2_005fnum1_005fdescription_005fnobody.reuse(_jspx_th_custom_005faddtag_005f1);
    return false;
  }
}
