/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.50
 * Generated at: 2026-04-17 00:29:45 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class register_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/WEB-INF/tld/courses.tld", Long.valueOf(1776385783544L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fp1_005fcourseFee_0026_005fcourses_005fnobody;

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fp1_005fcourseFee_0026_005fcourses_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fp1_005fcourseFee_0026_005fcourses_005fnobody.release();
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("    <title>Registration Result</title>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("\n");
      p1.Student student = null;
      student = (p1.Student) _jspx_page_context.getAttribute("student", jakarta.servlet.jsp.PageContext.REQUEST_SCOPE);
      if (student == null){
        student = new p1.Student();
        _jspx_page_context.setAttribute("student", student, jakarta.servlet.jsp.PageContext.REQUEST_SCOPE);
      }
      out.write('\n');
      org.apache.jasper.runtime.JspRuntimeLibrary.introspecthelper(_jspx_page_context.findAttribute("student"), "name", request.getParameter("name"), request, "name", false);
      out.write('\n');
      org.apache.jasper.runtime.JspRuntimeLibrary.introspecthelper(_jspx_page_context.findAttribute("student"), "roll", request.getParameter("roll"), request, "roll", false);
      out.write('\n');
      out.write('\n');

    // Retrieve selected courses
    String[] selected = request.getParameterValues("courses");
    String coursesCsv = "";
    if (selected != null) {
        // join into comma-separated string
        StringBuilder sb = new StringBuilder();
        for (int i = 0; i < selected.length; i++) {
            sb.append(selected[i]);
            if (i < selected.length - 1) sb.append(",");
        }
        coursesCsv = sb.toString();
    }
    // store courses in bean
    ((p1.Student)request.getAttribute("student")).setCourses(coursesCsv);

      out.write("\n");
      out.write("\n");
      out.write("<h2>Course Registration Confirmation</h2>\n");
      out.write("<p><strong>Name:</strong> ");
      out.print( request.getAttribute("student") != null ? ((p1.Student)request.getAttribute("student")).getName() : "" );
      out.write("</p>\n");
      out.write("<p><strong>Roll:</strong> ");
      out.print( request.getAttribute("student") != null ? ((p1.Student)request.getAttribute("student")).getRoll() : "" );
      out.write("</p>\n");
      out.write("<p><strong>Selected Courses:</strong> ");
      out.print( coursesCsv );
      out.write("</p>\n");
      out.write("\n");
      out.write("<!-- Use custom tag to calculate and display total fee; it also sets page attribute 'totalFee' -->\n");
      //  p1:courseFee
      p1.CourseFeeTag _jspx_th_p1_005fcourseFee_005f0 = (p1.CourseFeeTag) _005fjspx_005ftagPool_005fp1_005fcourseFee_0026_005fcourses_005fnobody.get(p1.CourseFeeTag.class);
      _jspx_th_p1_005fcourseFee_005f0.setPageContext(_jspx_page_context);
      _jspx_th_p1_005fcourseFee_005f0.setParent(null);
      // /register.jsp(37,0) name = courses type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_p1_005fcourseFee_005f0.setCourses( coursesCsv );
      int _jspx_eval_p1_005fcourseFee_005f0 = _jspx_th_p1_005fcourseFee_005f0.doStartTag();
      if (_jspx_th_p1_005fcourseFee_005f0.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return;
      }
      _005fjspx_005ftagPool_005fp1_005fcourseFee_0026_005fcourses_005fnobody.reuse(_jspx_th_p1_005fcourseFee_005f0);
      out.write('\n');
      out.write('\n');

    // Retrieve computed total from tag
    Double totalFee = (Double) pageContext.getAttribute("totalFee");
    if (totalFee == null) totalFee = 0.0;
    // store in bean
    ((p1.Student)request.getAttribute("student")).setTotalFee(totalFee);

    // Persist registration via JDBC (SQLite)
    java.sql.Connection conn = null;
    java.sql.PreparedStatement ps = null;
    try {
        Class.forName("org.sqlite.JDBC");
        String dbPath = "/home/psw/Projects/SSP/db/ssp61.db";
        conn = java.sql.DriverManager.getConnection("jdbc:sqlite:" + dbPath);
        java.sql.Statement st = conn.createStatement();
        st.executeUpdate("CREATE TABLE IF NOT EXISTS registrations (id INTEGER PRIMARY KEY AUTOINCREMENT, name TEXT, roll TEXT, courses TEXT, total REAL)");
        ps = conn.prepareStatement("INSERT INTO registrations(name, roll, courses, total) VALUES (?,?,?,?)");
        ps.setString(1, ((p1.Student)request.getAttribute("student")).getName());
        ps.setString(2, ((p1.Student)request.getAttribute("student")).getRoll());
        ps.setString(3, ((p1.Student)request.getAttribute("student")).getCourses());
        ps.setDouble(4, totalFee);
        ps.executeUpdate();
        out.println("<p><em>Registration saved to database.</em></p>");
    } catch (Exception e) {
        out.println("<p style='color:red;'>Error saving registration: " + e.getMessage() + "</p>");
    } finally {
        try { if (ps != null) ps.close(); } catch(Exception _e) {}
        try { if (conn != null) conn.close(); } catch(Exception _e) {}
    }

      out.write("\n");
      out.write("\n");
      out.write("<p><a href=\"registration_form.html\">Register another student</a></p>\n");
      out.write("\n");
      out.write("</body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
