/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.50
 * Generated at: 2026-04-17 00:17:29 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class generate_005fbill_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {


    // Declaration Tag: Tax calculation method (GST at 18%)
    public double calculateTax(double amount) {
        return amount * 0.18;
    }

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("    <title>Detailed Bill</title>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("\n");
      out.write('\n');
      out.write('\n');

    // Implicit Objects: request & session
    String customerName = request.getParameter("customerName");
    if (customerName == null) customerName = "";
    session.setAttribute("customerName", customerName);
    
    String product = request.getParameter("product");
    double price = 0.0;
    int quantity = 0;
    try { price = Double.parseDouble(request.getParameter("price")); } catch(Exception e) { price = 0.0; }
    try { quantity = Integer.parseInt(request.getParameter("quantity")); } catch(Exception e) { quantity = 0; }
    
    // Edge Case: Redirect immediately if quantity or price is 0 using 'response'
    if(quantity <= 0 || price <= 0) {
        response.sendRedirect("thankyou.jsp?error=invalid");
        return; 
    }

    // Scriptlet Tag: Calculate total bill amount and discount
    double totalAmount = price * quantity;
    double discount = 0;
    
    if (totalAmount > 5000) {
        discount = totalAmount * 0.10; // 10% discount for orders > ₹5000
    }
    
    double amountAfterDiscount = totalAmount - discount;
    double tax = calculateTax(amountAfterDiscount);
    double finalAmount = amountAfterDiscount + tax;
    
    // Implicit Object 'application': Maintain customer visit counter
    Integer customerCount = (Integer) application.getAttribute("customerCount");
    if (customerCount == null) {
        customerCount = 1;
    } else {
        customerCount += 1;
    }
    application.setAttribute("customerCount", customerCount);

      out.write("\n");
      out.write("\n");
      out.write("<h2>Invoice for ");
      out.print( session.getAttribute("customerName") );
      out.write("</h2>\n");
      out.write("<table border=\"1\" cellpadding=\"5\">\n");
      out.write("    <tr>\n");
      out.write("        <th>Product Name</th>\n");
      out.write("        <th>Quantity</th>\n");
      out.write("        <th>Total Price</th>\n");
      out.write("    </tr>\n");
      out.write("    <tr>\n");
      out.write("        <td>");
      out.print( product );
      out.write("</td>\n");
      out.write("        <td>");
      out.print( quantity );
      out.write("</td>\n");
      out.write("        <td>₹");
      out.print( totalAmount );
      out.write("</td>\n");
      out.write("    </tr>\n");
      out.write("</table>\n");
      out.write("\n");
      out.write("<br>\n");
      out.write("<p><strong>Total Amount:</strong> ₹");
      out.print( totalAmount );
      out.write("</p>\n");
      out.write("<p><strong>Discount (10% on >₹5000):</strong> - ₹");
      out.print( discount );
      out.write("</p>\n");
      out.write("<p><strong>GST (18%):</strong> + ₹");
      out.print( tax );
      out.write("</p>\n");
      out.write("<h3><strong>Final Payable Amount:</strong> ₹");
      out.print( finalAmount );
      out.write("</h3>\n");
      out.write("\n");
      out.write("<hr>\n");
      out.write("<p><strong>Total Customers Visited:</strong> ");
      out.print( application.getAttribute("customerCount") );
      out.write("</p>\n");
      out.write("\n");
      out.write("<form action=\"thankyou.jsp\" method=\"post\">\n");
      out.write("    <input type=\"submit\" value=\"Confirm and Pay\">\n");
      out.write("</form>\n");
      out.write("\n");
      out.write("</body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
